######################################################################
### The function is used to define the font, size and other details 
### of the plot generated by ggplot2. Save the plot to a .PDF file.
### Add ('+') the function to ggplot() function at approriate position.
######################################################################

guang_JD_plot_theme <- function()
{
  theme_classic() +  
    # set axis text color to "black"
    theme(axis.text = element_text(color = "black")) +
    # x and y axis text(number notation) set to 8.0 pt
    theme(axis.text = element_text(size = 8.0) ) + 
    # axis title(explain what datasets X or Y axis stands for): set to 10pt
    theme( axis.title = element_text(size = 10 ) ) +
    # set legend text the same size as axis text
    theme(legend.text = element_text(size = 8.0))+
    
    # set x and y axis line thickness to 0.75 pt
    theme( axis.line = element_line(size = 0.75/2.134, linetype = "solid")) + 
    # relative to default tickness size = 1 get 2.134 pt
    
    # set x and y axis ticks(short line beside number) with thickness of 0.5 pt
    theme( axis.ticks = element_line(size = 0.5/2.134) ) + 
    
    # remove legend box background(default is white)
    theme(legend.background=element_blank()) + 
    
    # axis tick length 0.04 inch
    theme(axis.ticks.length = unit(0.04, "in")) 
  
  
}
